<?php
/**
 * Created by PhpStorm.
 * User: air
 * Date: 14-7-27
 * Time: 上午8:25
 */

namespace cabbage\widgets;


use Yii;

class AceAsset extends AssetBundle{

    public $depends = [
        'yii\bootstrap\BootstrapPluginAsset',
        'cabbage\widgets\GritterAsset',
    ];

    public function init()
    {
        $this->setupAssets('css', [
            'css/font-awesome.min',
            'css/ace.min',
            'css/ace-rtl.min',
            'css/ace-skins.min',
        ]);
        $this->setupAssets('js', [
            'js/ace-extra.min',
            'js/ace-elements.min',
            'js/ace.min',
        ]);
        parent::init(); // TODO: Change the autogenerated stub
    }

} 