<?php
/**
 * Created by PhpStorm.
 * User: air
 * Date: 14-7-27
 * Time: 上午8:25
 */

namespace cabbage\widgets;


use Yii;

class EditableAsset extends AssetBundle{
    public $depends = [
        'yii\bootstrap\BootstrapPluginAsset'
    ];
    public function init()
    {
        $this->setupAssets('css', [
            'css/bootstrap-editable',
        ]);
        $this->setupAssets('js', [
            'js/x-editable/bootstrap-editable.min',
            'js/x-editable/ace-editable.min',
        ]);
        parent::init(); // TODO: Change the autogenerated stub
    }
}