<?php
/**
 * Created by PhpStorm.
 * User: air
 * Date: 14-7-27
 * Time: 上午9:27
 */

namespace cabbage\widgets;


use Yii;

class SideNavAsset extends AssetBundle{
    public $depends = [
      'cabbage\widgets\AceAsset'
    ];
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

} 