<?php
/**
 * Created by PhpStorm.
 * User: air
 * Date: 14-7-27
 * Time: 上午8:25
 */

namespace cabbage\widgets;


use Yii;

/**
 * Class WysiwygAsset 微型、开源的Bootstrap所见即所得（WYSIWYG）富文本编辑
 * @package cabbage\widgets
 */
class WysiwygAsset extends AssetBundle{
    public $depends = [
        'yii\bootstrap\BootstrapPluginAsset'
    ];
    public function init()
    {
        $this->setupAssets('js', [
            'js/bootstrap-wysiwyg.min',
        ]);
        parent::init(); // TODO: Change the autogenerated stub
    }
}